import { prisma } from "../configs/prisma.js";
import axios from "axios";
import * as Sentry from "@sentry/node";

export const connectMeta = async (req, res) => {
    try {
        const { userId } = req.auth();
        const { accessToken } = req.body;

        if (!accessToken) {
            return res.status(400).json({ message: "Access token is required" });
        }

        // We can verify the token, but for now just save it
        await prisma.user.update({
            where: { id: userId },
            data: { metaAccessToken: accessToken }
        });

        res.json({ message: "Meta account connected successfully" });
    } catch (error) {
        Sentry.captureException(error);
        console.error(error);
        res.status(500).json({ message: "Failed to connect Meta account" });
    }
}

export const getMetaPages = async (req, res) => {
    try {
        const { userId } = req.auth();

        const user = await prisma.user.findUnique({ where: { id: userId } });
        if (!user || !user.metaAccessToken) {
            return res.status(400).json({ message: "Meta account not connected" });
        }

        const response = await axios.get(`https://graph.facebook.com/v19.0/me/accounts?access_token=${user.metaAccessToken}`);

        res.json(response.data.data); // Array of pages
    } catch (error) {
        Sentry.captureException(error);
        console.error(error?.response?.data || error.message);
        res.status(500).json({ message: "Failed to fetch Meta pages" });
    }
}

export const publishToMeta = async (req, res) => {
    try {
        const { userId } = req.auth();
        const { pageId, pageAccessToken, imageUrl, message, platform = "facebook" } = req.body;

        if (!imageUrl) return res.status(400).json({ message: "Image URL is required" });
        if (!pageId || !pageAccessToken) return res.status(400).json({ message: "Page credentials required" });

        if (platform === "facebook") {
            const response = await axios.post(`https://graph.facebook.com/v19.0/${pageId}/photos`, {
                url: imageUrl,
                message: message || "Generated by AdAlchemist",
                access_token: pageAccessToken
            });
            return res.json({ message: "Successfully published to Facebook!", id: response.data.id });
        }

        if (platform === "instagram") {
            // Instagram requires getting the IG Account ID associated with the FB Page first.
            const igResponse = await axios.get(`https://graph.facebook.com/v19.0/${pageId}?fields=instagram_business_account&access_token=${pageAccessToken}`);

            const igAccountId = igResponse.data?.instagram_business_account?.id;
            if (!igAccountId) {
                return res.status(400).json({ message: "No Instagram Business Account linked to this Facebook Page." });
            }

            // Step 1: Create media container
            const containerResponse = await axios.post(`https://graph.facebook.com/v19.0/${igAccountId}/media`, {
                image_url: imageUrl,
                caption: message || "Generated by AdAlchemist",
                access_token: pageAccessToken
            });

            const creationId = containerResponse.data.id;

            // Step 2: Publish media container
            const publishResponse = await axios.post(`https://graph.facebook.com/v19.0/${igAccountId}/media_publish`, {
                creation_id: creationId,
                access_token: pageAccessToken
            });

            return res.json({ message: "Successfully published to Instagram!", id: publishResponse.data.id });
        }

    } catch (error) {
        Sentry.captureException(error);
        console.error(error?.response?.data || error.message);
        res.status(500).json({ message: error?.response?.data?.error?.message || "Failed to publish to Meta" });
    }
}
